### PR TITLE
Fixing trinkets support. (1.17-dev)

### PR DESCRIPTION
**Pull request by tort-oise**
Hi. I'm not sure if this is intentional or not, but the 1.17 mod Trinkets' trinket tags becomes broken because of this mod.
As attached below, it fails to load these tags, as it is missing a reference.
image

The mod is listed as having trinkets on CurseForge, but does not include the Trinkets API-ish mod as a dependency, and has several broken references (I am not sure if these items were removed or not, but the references are broken). 

I removed 7 files, and edited another, leaving only one trinket reference that didn't break (`arcanus:gloves_of_the_hippocratic_oath`), built the new file, and the Trinkets mod loads fine without it, not breaking any of the tags that Trinkets uses. 
As Trinkets is not listed as a dependency, I'm assuming this isn't intentional, and it breaks the functionality of several other mods which use the trinkets tags, along with the API. 

But then again, I want your feedback. Is this unintentional, and do you not use these tags/item references, or is this mod incompatible with the Trinkets API? This PR should be seen as more of an example, not something I'm fully willing to push into mainstream.

### CODE REVIEW

**Comment by tort-oise** [comment]
When I say "Trinkets is not listed as a dependency, I specifically mean this. 
image

Neither is it plastered onto the About page.
I would love more input about this, thank you.

**Comment by CammiePone** [comment]
Honestly the trinkets compat should just be yeeted entirely, but also I'm not really doing the 1.17 version anymore. 1.18 comes out in 4 days

**Comment by tort-oise** [comment]
I mostly posted this because someone came into a Discord server I'm in, and asked why their trinkets weren't working. If you're not gonna fix the 1.17 version, then 1.17 packs with this mod and Trinkets will just get broken. 
At least clean up after yourself if you're not gonna use a dependency.

**Comment by tort-oise** [comment]
If you're not going to use the Trinkets compat, would you prefer for the entire resources/data/trinkets folder to be removed?

**Comment by CammiePone** [comment]
Here's the thing, everything I did was what was supposed to be done. So that means either they're using an old version of Trinkets, an old version of Arcanus, or something is breaking the optional tag system from vanilla.

If you can provide more info, I can point to where the error lies.

See this part?

image

Yeah, that tells the game to _not_ break the tag if the item isn't found. So my bet is old version of Arcanus from before I already fixed the mistake, or some other mod managed to fuck up tag parsing.

Arcanus works fine in AOF4, it works fine in my own personal pack, so I would appreciate you not trying to say it's my fault when I'm doing everything exactly as you're supposed to to ensure it doesn't break.

**Comment by CammiePone** [comment]
Just for some further proof: Arcanus running with Botania without issue. Belts work, rings work, and everything else works.

image

**Comment by CammiePone** [comment]
I'm 99% certain y'all are using Arcanus 1.15, instead of Arcanus 1.23. 1.15 is when the jsons were first added, and only a week later were they changed to be fixed so they wouldn't cause issues in 1.16. 1.15 also lacked `arcanus:gloves_of_the_hippocratic_oath` in its jsons entirely, which is why it never showed up in the logs.

**Comment by tort-oise** [comment]
Long story short: I'm not the one who used 1.15, the user in our Discord apparently did. Probably on my side's fault for not checking that. 
I never said it was your fault, but as these items seemingly weren't in the game, I thought you just forgot to remove these .json tags, as Arcanus is no longer listed as a dependency.

**Pull request closed without merging**
