### PR TITLE
Make Arcane Barrier obtainable

### LINKED ISSUE #28: [Question] Arcane Barrier Spell Book
I wanted to ask about this spell's book, is it only obtainable through creative or is there another way?

### PR DESCRIPTION
**Pull request by N2D4**
Fixes an off-by-one error that prevented Arcane Barrier from generating in the wild.

Fixes #28

### CODE REVIEW

**Comment by CammiePone** [comment]
Wait did that actually change when going to 1.18? That's so dumb. Before that would cause an index out of bounds exception :despair:

**Comment by N2D4** [comment]
> Wait did that actually change when going to 1.18? That's so dumb. Before that would cause an index out of bounds exception :despair:

That might actually still be the case, I'm not aware of any changes (nor of the absence thereof). In that case, `Arcanus.SPELL.getEntries().get(RAND.nextInt(Arcanus.SPELL.getEntries().size())) ` could work?

**Comment by CammiePone** [comment]
Best way to test is just run that method over and over again in a println every tick to find out :D

**Comment by CammiePone** [comment]
I mean, you could also just print out the size and see if it says 7 or 8 (used to say 8, which was out of bounds), but that's the smart way and we dont use our brains in this household

**Comment by N2D4** [comment]
> I mean, you could also just print out the size and see if it says 7 or 8 (used to say 8, which was out of bounds), but that's the smart way and we dont use our brains in this household

8 should be correct though, no? Because `RAND.nextInt(max)` generates numbers in `[0, max)`, so `max` is never included

**Comment by CammiePone** [comment]
Actually, wait a second. I think I know what happened, and yes your code should be fine (though I think the first spell wont be obtainable now). Im stupid and when I changed that code back in 1.17, I didnt do it right.

**Comment by CammiePone** [comment]
I'll just merge and make some fixes later today if necessary. My itch to program is back, albeit not for Minecraft modding, and I've got a few things I wanna get done today.

**Comment by N2D4** [comment]
Cool, thanks!

**Pull request merged**
